import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{Tag}from'../server/tag.js';import{ARENAS}from'../server/maps.js';import{stickValue}from'../src/controls.js';import{GameRuntime}from'@manaty/retro-museum-sdk/runtime';
const people=n=>Array.from({length:n},(_,i)=>({id:'p'+i,number:i+1})),advance=(g,s)=>{for(let t=0;t<s;t+=1/60)g.advance(1/60);},game=(n=2,options={})=>new Tag(people(n),null,{seed:31,...options});
function floor(p,x=600){Object.assign(p,{x,y:633,vx:0,vy:0,grounded:true,ground:0,jumps:0});}
test('roster is capped at eight and randomized tagger is reproducible only with a fixed seed',()=>{const a=game(10),b=game(8);assert.equal(a.players.length,8);assert.deepEqual(a.order,b.order);const starts=new Set(Array.from({length:25},(_,i)=>game(8,{seed:(i+1)*971}).tagger));assert.ok(starts.size>3);a.addPlayer({id:'late'});assert.equal(a.players.length,8);});
test('joystick ring clamps distance, normalizes input, rejects invalid and spectator actions',()=>{const s=stickValue(300,100,{left:0,top:0,width:200,height:200});assert.equal(s.x,1);assert.ok(s.offsetX<=75);const g=game();g.action('p0','tagInput',{x:999,y:999});assert.ok(g.players[0].inputX<1);for(const v of [{x:NaN,y:0},{x:Infinity,y:0},{x:'1',y:0},{x:0,y:0,jump:1}])assert.throws(()=>g.action('p0','tagInput',v),/invalidInput/);assert.throws(()=>g.action('stranger','tagInput',{x:1,y:0}),/spectator/);});
test('movement responds, releases and expires after a missing heartbeat without pausing others',()=>{const g=game(),p=g.players[0];floor(p);g.action(p.id,'tagInput',{x:1,y:0});advance(g,.2);assert.ok(p.x>620);advance(g,.5);const x=p.x;advance(g,.6);assert.equal(p.x,x);g.action(p.id,'tagInput',{x:-1,y:0});advance(g,.1);g.release(p.id);advance(g,.3);const stopped=p.x;advance(g,.2);assert.equal(p.x,stopped);assert.deepEqual(g.status().requiredPlayers,[]);});
test('jump rises, double jump needs release and cannot repeat indefinitely; single jump option works',()=>{for(const doubleJump of [true,false]){const g=game(2,{doubleJump}),p=g.players[0];floor(p);g.action(p.id,'tagInput',{x:0,y:-1});advance(g,.15);assert.ok(p.y<590);const jumps=p.jumps;g.action(p.id,'tagInput',{x:0,y:-1});advance(g,.05);assert.equal(p.jumps,jumps);g.action(p.id,'tagInput',{x:0,y:0});g.action(p.id,'tagInput',{x:0,y:0,jump:true});advance(g,.02);assert.equal(p.jumps,doubleJump?2:1);g.action(p.id,'tagInput',{x:0,y:0});g.action(p.id,'tagInput',{x:0,y:-1});advance(g,.05);assert.ok(p.jumps<=2);advance(g,3);assert.ok(p.grounded);}});
test('solid platform lands from above, blocks underneath and prevents horizontal penetration',()=>{const g=game(),p=g.players[0],b=g.arena.platforms[1];Object.assign(p,{x:b.x+90,y:b.y-50,vy:250,vx:0});advance(g,.2);assert.equal(p.y,b.y-17);assert.ok(p.grounded);Object.assign(p,{x:b.x+90,y:b.y+b.h+18,vy:-460});advance(g,.03);assert.ok(p.y>=b.y+b.h+17);Object.assign(p,{x:b.x-14,y:b.y+10,vx:260,inputX:1,inputUntil:5});advance(g,.05);assert.ok(p.x+13<=b.x);});
test('jelly allows upward passage and deliberate drop; springs and speed pads apply their effects',()=>{const g=game(),p=g.players[0],j=g.arena.platforms.findIndex(b=>b.type==='jelly'),b=g.arena.platforms[j];Object.assign(p,{x:b.x+60,y:b.y-17,grounded:true,ground:j});g.action(p.id,'tagInput',{x:0,y:1});advance(g,.2);assert.ok(p.y>b.y+17);Object.assign(p,{x:b.x+60,y:b.y+40,vy:-460,dropUntil:0});advance(g,.2);assert.ok(p.y<b.y-17);const spring=g.arena.platforms.find(b=>b.type==='spring');Object.assign(p,{x:spring.x+30,y:spring.y-18,vy:30});advance(g,.04);assert.ok(p.vy<-600);assert.ok(g.events.some(e=>e.type==='spring'));const speed=g.arena.platforms.find(b=>b.type==='speed');Object.assign(p,{x:speed.x+30,y:speed.y-18,vy:30});advance(g,.04);assert.ok(p.boostUntil>g.time);});
test('touch transfers tag, locks immediate returns and emits one event',()=>{const g=game();g.tagger='p0';g.tagLock=0;floor(g.players[0],590);floor(g.players[1],612);advance(g,.02);assert.equal(g.tagger,'p1');assert.ok(g.players[0].immuneUntil>g.time+1);advance(g,.8);assert.equal(g.tagger,'p1');assert.equal(g.events.filter(e=>e.type==='tag').length,1);advance(g,1);assert.equal(g.tagger,'p0');});
test('solid wall occlusion rejects tagging through platforms',()=>{const g=game(),b=g.arena.platforms[1];assert.equal(g.lineBlocked({x:b.x+60,y:b.y-3},{x:b.x+60,y:b.y+b.h+3}),true);assert.equal(g.lineBlocked({x:600,y:600},{x:610,y:600}),false);g.tagger='p0';g.tagLock=0;Object.assign(g.players[0],{x:b.x+60,y:b.y-17,vy:0});Object.assign(g.players[1],{x:b.x+60,y:b.y+b.h+17,vy:0});advance(g,.02);assert.equal(g.tagger,'p0');});
test('round expiry awards all survivors, intermission rotates arena and tagger fairly',()=>{const g=game(4,{roundSeconds:30,rounds:3});const first=g.tagger;advance(g,30.05);assert.equal(g.phase,'intermission');assert.equal(g.lastLoser,first);assert.equal(g.players.find(p=>p.id===first).score,0);assert.equal(g.players.reduce((n,p)=>n+p.score,0),3);advance(g,4.1);assert.equal(g.round,2);assert.equal(g.arena.id,'garden');assert.notEqual(g.tagger,first);});
test('full matches with two and eight players finish, score totals and tied winners are consistent',()=>{for(const count of [2,8]){const g=game(count,{roundSeconds:30,rounds:3});advance(g,100);assert.ok(g.ended);assert.equal(g.round,3);assert.equal(g.players.reduce((n,p)=>n+p.score,0),(count-1)*3);assert.equal(g.winners.length===1?g.winners[0]:'draw',g.winner);assert.throws(()=>g.action('p0','tagInput',{x:0,y:0}),/roundOver/);}});
test('host end resolves equal scores, save/resume preserves match and clears stuck controls',()=>{const g=game(8);g.action('p0','tagInput',{x:1,y:0});advance(g,1);const saved=g.save(),restored=new Tag([],saved);assert.equal(restored.tagger,g.tagger);assert.equal(restored.seed,g.seed);assert.deepEqual(restored.snapshot(),g.snapshot());g.release();advance(g,2);advance(restored,2);assert.deepEqual(restored.snapshot(),g.snapshot());const draw=game();draw.action(null,'hostTimeUp');assert.equal(draw.winner,'draw');assert.deepEqual(draw.winners,['p0','p1']);});
test('all arena spawns land safely, geometry fits and rotation has three different regions',()=>{for(const arena of ARENAS){const g=game(8,{arena:arena.id});advance(g,5);for(const p of g.players){assert.ok(p.y>=0&&p.y<=633);assert.ok(Number.isFinite(p.x));}assert.equal(g.players.length,8);assert.ok(arena.platforms.every(p=>p.x>=0&&p.x+p.w<=1200));}});
test('QuickJS sustains eight-player input, physics and compact snapshots within runtime budgets',async()=>{const pack=JSON.parse(await readFile('dist/game.rmg.json')),g=new GameRuntime(pack,people(8));try{for(let i=0;i<400;i++){for(let p=0;p<8;p++)if(i%2===0)g.action('p'+p,'tagInput',{x:(i%80<40?1:-1)*(p%2?1:-1),y:i%20===0?-1:0});g.advance(.05);if(i%10===0)assert.ok(JSON.stringify(g.snapshot()).length<20000);}assert.equal(g.snapshot().players.length,8);assert.deepEqual(g.metadata.requiredPlayers,[]);assert.ok(g.save().seed);}finally{g.dispose();}});
