import test from'node:test';import assert from'node:assert/strict';import{mkdir}from'node:fs/promises';import{chromium}from'playwright';import{loadGame,createGameHost}from'@manaty/retro-museum-sdk/host';
test('real host: eight phones, joystick plus jump, tag, pause, disconnect, results and replay',{timeout:180000},async()=>{const definition=await loadGame(new URL('../dist/game.rmg.json',import.meta.url)),host=await createGameHost({definitions:[definition]});await new Promise(r=>host.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+host.server.address().port,browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})}),errors=[];
const post=async(path,body,token)=>{const r=await fetch(base+path,{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify(body)});assert.ok(r.ok,await r.clone().text());return r.json();};const until=async fn=>{for(let i=0;i<600;i++){if(await fn())return;await new Promise(r=>setTimeout(r,40));}throw Error('Timeout');};
try{const room=await post('/api/rooms',{game:'tag',language:'fr'}),party=host.rooms.get(room.id).party;await post('/api/rooms/'+room.id+'/control',{action:'configure',options:{rounds:1,roundSeconds:30}},room.hostToken);const display=await browser.newPage({viewport:{width:1440,height:1000}});display.on('pageerror',e=>errors.push(e.message));await display.goto(base+'/r/'+room.id+'#'+room.hostToken);const clients=[];async function add(name){const ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});await ctx.addInitScript(name=>{if(window===top){localStorage.setItem('museum-player-profile',JSON.stringify({name}));localStorage.setItem('museum-player-language','fr');}},name);const page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/j/'+room.id);await until(()=>party.players.some(p=>p.name===name));const id=party.players.find(p=>p.name===name).id,frame=page.frameLocator('.stage iframe');clients.push({id,page,frame,ctx});return clients.at(-1);}
for(const name of ['Alice','Benoît','Camille','Diego','Emma','Félix','Gaby','Hugo'])await add(name);await mkdir('docs/screenshots',{recursive:true});await display.screenshot({path:'docs/screenshots/lobby.png'});await display.locator('[data-control=start]').click();await until(()=>party.phase==='playing');const client=clients[0],initial=party.engine.snapshot().players[0],ring=client.frame.locator('.joystick');await ring.waitFor();const box=await ring.boundingBox(),point={clientX:box.width-10,clientY:box.height/2};
// Pointer event coordinates are viewport-relative inside the iframe.
const rect=await ring.evaluate(el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height};});await ring.dispatchEvent('pointerdown',{pointerId:11,clientX:rect.x+rect.w-12,clientY:rect.y+rect.h/2});await until(()=>party.engine.snapshot().players[0].x>initial.x+15);await client.frame.locator('[data-jump]').dispatchEvent('pointerdown',{pointerId:12});await until(()=>party.engine.snapshot().players[0].y<initial.y-20);await client.frame.locator('[data-jump]').dispatchEvent('pointerup',{pointerId:12});await ring.dispatchEvent('pointerup',{pointerId:11});await until(()=>Math.abs(party.engine.snapshot().players[0].vx)<1);assert.equal(await ring.locator('.joystick-knob').evaluate(el=>el.style.transform),'translate(-50%, -50%)');await display.frameLocator('.stage iframe').locator('[data-sound]').click();await display.screenshot({path:'docs/screenshots/display.png'});await client.page.screenshot({path:'docs/screenshots/controller.png'});
await post('/api/rooms/'+room.id+'/control',{action:'pause'},room.hostToken);const paused=party.engine.snapshot().time;await new Promise(r=>setTimeout(r,250));assert.equal(party.engine.snapshot().time,paused);await post('/api/rooms/'+room.id+'/control',{action:'resume'},room.hostToken);
// Deterministic contact fixture runs through real QuickJS physics and publishes real state.
let saved=party.engine.save();saved.tagger=clients[0].id;saved.tagLock=0;saved.players.forEach((p,i)=>Object.assign(p,{x:i<2?590+i*20:60+i*145,y:633,vx:0,vy:0,immuneUntil:0,inputUntil:0}));party.engine.dispose();party.engine=party.createEngine(party.players,saved);await until(()=>party.engine.snapshot().tagger===clients[1].id);await until(()=>client.frame.locator('.chase-status').textContent().then(t=>t.includes('Évite')||t.includes('Cours')));
await clients[7].ctx.close();await until(()=>party.players.find(p=>p.id===clients[7].id).connected===false);assert.equal(party.phase,'playing');const left=party.engine.snapshot().left;await new Promise(r=>setTimeout(r,150));assert.ok(party.engine.snapshot().left<left);
// Complete this 30-second match using the live timer, without changing the deadline.
await until(()=>party.phase==='solved'||party.engine.snapshot().left<11);await until(()=>party.phase==='solved');assert.ok(party.engine.snapshot().winners.length>0);await client.frame.locator('[data-again]').waitFor();await display.screenshot({path:'docs/screenshots/victory.png'});const old=party.id;await client.frame.locator('[data-again]').click();await until(()=>party.id!==old);await until(()=>party.phase==='playing');assert.equal(party.engine.snapshot().players.length,7);
// A late arrival spectates this match, but is eligible after replay.
const late=await add('Iris');assert.equal(party.players.find(p=>p.id===late.id).spectator,true);saved=party.engine.save();saved.left=.08;saved.players.forEach(p=>p.score=0);party.engine.dispose();party.engine=party.createEngine(party.players.filter(p=>!p.spectator),saved);await until(()=>party.phase==='solved');assert.equal(party.engine.snapshot().winner,'draw');const old2=party.id;await client.frame.locator('[data-again]').click();await until(()=>party.id!==old2);await until(()=>party.phase==='playing');assert.equal(party.engine.snapshot().players.length,8);assert.equal(party.players.find(p=>p.id===late.id).spectator,false);saved=party.engine.save();saved.left=.08;saved.players[0].score=9;party.engine.dispose();party.engine=party.createEngine(party.players.filter(p=>!p.spectator),saved);await until(()=>party.phase==='solved');assert.equal(party.engine.snapshot().winner,clients[0].id);await client.frame.locator('[data-again]').click();await until(()=>party.phase==='intro'||party.phase==='playing');await post('/api/rooms/'+room.id+'/control',{action:'end'},room.hostToken);await client.frame.locator('[data-again]').waitFor();assert.deepEqual(errors,[]);assert.ok(!party.failed);
}finally{await browser.close();await host.close();}});
