import{ARENAS,arenaFor,WIDTH,HEIGHT,FLOOR}from'./maps.js';
export const COLORS=['#ffbf69','#6bd5d0','#ee86b4','#b5a0ff','#9cdc83','#7fbfff','#f09272','#ecdd79'];
const clone=x=>JSON.parse(JSON.stringify(x)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),finite=v=>typeof v==='number'&&Number.isFinite(v);
export class Tag{
 constructor(players=[],saved=null,options={}){
  this.options={roundSeconds:[30,45,60].includes(options.roundSeconds)?options.roundSeconds:45,rounds:[1,3,5,7].includes(options.rounds)?options.rounds:5,arena:['rotation',...ARENAS.map(a=>a.id)].includes(options.arena)?options.arena:'rotation',doubleJump:options.doubleJump!==false};
  this.seed=(options.seed>>>0)||((Math.random()*4294967295)>>>0)||1;this.players=players.slice(0,8).map((p,i)=>({id:p.id,number:p.number||i+1,color:COLORS[i],score:0,tagTime:0,x:0,y:0,vx:0,vy:0,face:1,grounded:false,ground:-1,lastGround:-1e3,jumps:0,jumpUntil:0,dropUntil:0,immuneUntil:0,boostUntil:0,inputX:0,inputUntil:0,jumpHeld:false,dropHeld:false}));
  this.phase='chase';this.round=1;this.time=0;this.left=this.options.roundSeconds;this.intermission=0;this.tagger=null;this.tagLock=0;this.lastLoser=null;this.winner=null;this.winners=[];this.ended=false;this.events=[];this.serial=0;this.accumulator=0;this.order=this.players.map(p=>p.id);for(let i=this.order.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[this.order[i],this.order[j]]=[this.order[j],this.order[i]];}this.resetRound();
  if(saved){for(const k of ['options','seed','players','phase','round','time','left','intermission','tagger','tagLock','lastLoser','winner','winners','ended','events','serial','accumulator','order'])if(saved[k]!==undefined)this[k]=clone(saved[k]);this.release();}
 }
 get arena(){return arenaFor(this.options.arena,this.round);}
 random(){let x=this.seed;x^=x<<13;x^=x>>>17;x^=x<<5;this.seed=x>>>0;return this.seed/4294967296;}
 emit(type,data={}){this.events.push({id:++this.serial,type,time:this.time,...data});if(this.events.length>32)this.events.shift();}
 resetRound(){this.left=this.options.roundSeconds;this.phase='chase';this.tagger=this.order[(this.round-1)%Math.max(1,this.order.length)]||null;this.tagLock=this.time+1.1;this.players.forEach((p,i)=>{const [x,y]=this.arena.spawns[i];Object.assign(p,{x,y,vx:0,vy:0,grounded:false,ground:-1,lastGround:-1e3,jumps:0,jumpUntil:0,dropUntil:0,immuneUntil:0,boostUntil:0,inputX:0,inputUntil:0,jumpHeld:false,dropHeld:false});});this.emit('round',{round:this.round,tagger:this.tagger,arena:this.arena.id});}
 action(id,action,value={}){if(id===null&&action==='hostTimeUp')return this.finish();const p=this.players.find(p=>p.id===id);if(!p)throw Error('spectator');if(this.ended||this.phase!=='chase')throw Error('roundOver');if(action!=='tagInput')throw Error('invalidGameAction');if(!value||!finite(value.x)||!finite(value.y)||value.jump!==undefined&&typeof value.jump!=='boolean'||value.drop!==undefined&&typeof value.drop!=='boolean')throw Error('invalidInput');const norm=Math.max(1,Math.hypot(value.x,value.y)),x=clamp(value.x/norm,-1,1),y=clamp(value.y/norm,-1,1),jump=value.jump===true||y<-.65,drop=value.drop===true||y>.65;p.inputX=Math.abs(x)<.12?0:x;p.inputUntil=this.time+.3;if(jump&&!p.jumpHeld)p.jumpUntil=this.time+.13;if(drop&&!p.dropHeld&&p.ground>=0&&this.arena.platforms[p.ground]?.type==='jelly'){p.dropUntil=this.time+.24;p.y+=5;p.grounded=false;p.ground=-1;p.vy=80;p.lastGround=-1e3;this.emit('drop',{player:p.id});}p.jumpHeld=jump;p.dropHeld=drop;}
 release(id){for(const p of this.players)if(!id||p.id===id){p.inputX=0;p.inputUntil=0;p.jumpHeld=false;p.dropHeld=false;p.jumpUntil=0;}}
 addPlayer(){} // Arrivals during a match spectate; the host includes them on replay.
 body(p,dt){const input=p.inputUntil>this.time?p.inputX:0;if(!input&&p.inputUntil<=this.time){p.jumpHeld=false;p.dropHeld=false;}const boosted=p.boostUntil>this.time,speed=(p.id===this.tagger?275:260)*(boosted?1.4:1),target=input*speed,accel=(input?1700:2100)*dt;p.vx+=clamp(target-p.vx,-accel,accel);if(input)p.face=input<0?-1:1;
  if(p.jumpUntil>this.time){const coyote=p.grounded||this.time-p.lastGround<.1,air=this.options.doubleJump&&p.jumps<2;if(coyote||air){p.vy=-460;p.grounded=false;p.ground=-1;p.jumps=coyote?1:p.jumps+1;p.lastGround=-1e3;p.jumpUntil=0;this.emit('jump',{player:p.id,x:p.x,y:p.y,double:p.jumps>1});}}
  const platforms=this.arena.platforms;let dx=p.vx*dt,n=Math.max(1,Math.ceil(Math.abs(dx)/3));for(let i=0;i<n;i++){const nx=clamp(p.x+dx/n,14,WIDTH-14),left=nx-13,right=nx+13;const hit=platforms.find(b=>b.type!=='jelly'&&left<b.x+b.w&&right>b.x&&p.y+17>b.y+.1&&p.y-17<b.y+b.h-.1);if(hit){p.vx=0;break;}p.x=nx;}
  p.vy+=760*dt;const dy=p.vy*dt;n=Math.max(1,Math.ceil(Math.abs(dy)/3));p.grounded=false;p.ground=-1;for(let i=0;i<n;i++){const ny=p.y+dy/n;let hit=-1;for(let j=0;j<platforms.length;j++){const b=platforms[j];if(p.x+12<=b.x||p.x-12>=b.x+b.w)continue;if(b.type==='jelly'){if(this.time<p.dropUntil||dy<0||p.y+17>b.y+1)continue;}if(dy>=0&&p.y+17<=b.y+1&&ny+17>=b.y){hit=j;p.y=b.y-17;p.grounded=true;p.ground=j;p.lastGround=this.time;p.jumps=0;break;}if(dy<0&&b.type!=='jelly'&&p.y-17>=b.y+b.h-1&&ny-17<=b.y+b.h){hit=j;p.y=b.y+b.h+17;break;}}if(hit>=0){p.vy=0;break;}p.y=ny;}
  if(p.grounded){const b=platforms[p.ground];if(b.type==='spring'){p.vy=-675;p.grounded=false;p.ground=-1;p.lastGround=-1e3;p.jumps=1;this.emit('spring',{player:p.id,x:p.x,y:p.y});}if(b.type==='speed')p.boostUntil=this.time+.65;}
  if(p.y>HEIGHT+35||p.y<-500){const i=Math.max(0,this.players.findIndex(q=>q.id===p.id)),[x,y]=this.arena.spawns[i];p.x=x;p.y=y;p.vx=p.vy=0;p.immuneUntil=this.time+1;this.emit('respawn',{player:p.id});}
 }
 lineBlocked(a,b){const steps=Math.max(1,Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/3));for(let i=1;i<steps;i++){const x=a.x+(b.x-a.x)*i/steps,y=a.y+(b.y-a.y)*i/steps;if(this.arena.platforms.some(p=>p.type!=='jelly'&&x>p.x&&x<p.x+p.w&&y>p.y&&y<p.y+p.h))return true;}return false;}
 step(dt){this.time+=dt;if(this.phase==='intermission'){this.intermission-=dt;if(this.intermission<=0){this.round++;this.resetRound();}return;}if(this.phase!=='chase')return;this.left=Math.max(0,this.left-dt);const previous=new Map(this.players.map(p=>[p.id,{x:p.x,y:p.y}]));for(const p of this.players)this.body(p,dt);const tagger=this.players.find(p=>p.id===this.tagger);if(tagger)tagger.tagTime+=dt;
  // Check the swept relative path as well as final overlap, so fast crossings count.
  if(tagger&&this.time>=this.tagLock)for(const p of this.players){if(p===tagger||p.immuneUntil>this.time)continue;const a=previous.get(tagger.id),b=previous.get(p.id),rx=a.x-b.x,ry=(a.y-b.y)*.8,dx=(tagger.x-p.x)-rx,dy=(tagger.y-p.y)*.8-ry,len=dx*dx+dy*dy,t=len?clamp(-(rx*dx+ry*dy)/len,0,1):0;if(Math.hypot(rx+dx*t,ry+dy*t)>27||this.lineBlocked(tagger,p))continue;const old=this.tagger;this.tagger=p.id;this.tagLock=this.time+.85;tagger.immuneUntil=this.time+1.6;this.emit('tag',{from:old,player:p.id,x:p.x,y:p.y});break;}
  if(this.left<=0)this.endRound();
 }
 endRound(){this.lastLoser=this.tagger;for(const p of this.players)if(p.id!==this.tagger)p.score++;this.release();this.emit('roundEnd',{loser:this.lastLoser,round:this.round});if(this.round>=this.options.rounds)this.finish();else{this.phase='intermission';this.intermission=4;}}
 finish(){if(this.ended)return;this.ended=true;this.phase='finished';const best=Math.max(...this.players.map(p=>p.score));this.winners=this.players.filter(p=>p.score===best).map(p=>p.id);this.winner=this.winners.length===1?this.winners[0]:'draw';this.release();this.emit('win',{winners:this.winners});}
 advance(dt){if(this.ended||!finite(dt)||dt<=0)return false;this.accumulator+=Math.min(1,dt);while(this.accumulator>=1/60&&!this.ended){this.accumulator-=1/60;this.step(1/60);}return true;}
 status(){return{winner:this.winner,ended:this.ended,requiredPlayers:[]};}
 snapshot(id){return{phase:this.phase,time:this.time,round:this.round,rounds:this.options.rounds,left:this.left,intermission:this.intermission,tagger:this.tagger,tagLock:this.tagLock,lastLoser:this.lastLoser,winner:this.winner,winners:this.winners,arena:this.arena,options:this.options,players:this.players.map(({inputX,inputUntil,jumpHeld,dropHeld,jumpUntil,lastGround,dropUntil,...p})=>clone(p)),events:clone(this.events),you:id||null};}
 save(){return{...this.snapshot(),players:clone(this.players),seed:this.seed,serial:this.serial,order:this.order,ended:this.ended,accumulator:this.accumulator};}
}
