import{Scene,avatar}from'./art.js';import{Audio}from'./audio.js';import{tr}from'./i18n.js';import{stickValue,inputValue}from'./controls.js';import{Tag,COLORS}from'../server/tag.js';
const app=document.querySelector('#app'),audio=new Audio(),keys=new Set(),pending=new Map();let state,role,lang='en',scene,layoutKey='',match='',lastPhase='',lastEvent=0,lastRound=0,lastSecond=-1,stick=null,pointer=null,jumpHeld=false,dropHeld=false,sequence=0,lastSent=0,lastInput='',preview=null,selectionKey='';
const t=k=>tr(lang,k),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),tell=(type,data={})=>parent.postMessage({retroMuseum:1,type,...data},'*');
function toast(text){const el=document.querySelector('#notice');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2500);}
const enabled=()=>role==='controller'&&state?.phase==='playing'&&state.party.community?.phase==='chase'&&state.party.community.players.some(p=>p.id===state.party.you);
function send(action,value={}){const id=String(++sequence);return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(Error('connectionInterrupted'));},5000);pending.set(id,{resolve,reject,timer});tell('action',{id,action,value});});}
function input(force=false){if(!enabled())return;const value=inputValue(stick,keys,jumpHeld,dropHeld),text=JSON.stringify(value),now=performance.now();if(force||now-lastSent>=40&&text!==lastInput||now-lastSent>=90){lastSent=now;lastInput=text;send('tagInput',value).catch(e=>{if(!['roundOver','gameNotPlaying','oldMatch'].includes(e.message))toast(t('error'));});}}
function stop(){const held=stick||keys.size||jumpHeld||dropHeld;stick=null;pointer=null;jumpHeld=dropHeld=false;keys.clear();const knob=app.querySelector('.joystick-knob');if(knob)knob.style.transform='translate(-50%,-50%)';app.querySelector('[data-jump]')?.classList.remove('held');if(held)input(true);}
setInterval(()=>{if(enabled()&&(stick||keys.size||jumpHeld||dropHeld))input();},60);
function profiles(){return Object.fromEntries((state?.party.players||[]).map(p=>[p.id,p]));}
function setup(){scene?.destroy();const mobile=role==='controller';app.innerHTML=`<div class="tag-app ${mobile?'controller':'display'}"><header><div><div class="eyebrow">RETRO MUSEUM · PLAY TOGETHER</div><h1>${t('title')}</h1></div><div class="audio"><button data-sound aria-label="${t('sound')}">♪</button>${mobile?'':`<button data-music>${t('music')} ♪</button>`}</div></header><section class="scoreboard"></section><div class="arena-heading"><span class="arena-name"></span><span class="round-number"></span></div><div class="scene"><canvas id="arena" aria-label="${t('title')}"></canvas><div class="center-overlay" hidden></div><div class="tag-banner" role="status"></div><div class="timer"><b>45</b><span>SEC</span></div></div><section class="lobby"><p class="eyebrow">${t('tagline')}</p><h2>${t('ready')}</h2><p>${t('rules')}</p><div class="lineup"></div><p class="muted">${t('waiting')}</p></section>${mobile?`<section class="phone-controls"><div class="identity"><span class="portrait"></span><div><small>${t('yourPlayer')}</small><strong class="your-name"></strong><span class="chase-status" role="status"></span></div></div><div class="pads"><div class="joystick" role="group" aria-label="${t('hold')}"><span class="guide horizontal"></span><span class="guide vertical"></span><span class="axis top">↥</span><span class="axis bottom">⌄</span><span class="joystick-knob"></span></div><div class="action-pad"><button class="jump" data-jump>↥<span>${t('jump')}</span></button><button class="drop" data-drop>↓ ${t('drop')}</button></div></div><p class="help">${t('controls')}</p><p class="double"></p></section>`:''}<footer><span class="tagger-name"></span><div class="legend"><span class="jelly">● ${t('jelly')}</span><span class="spring">● ${t('spring')}</span><span class="speed">● ${t('speed')}</span></div></footer></div>`;scene=new Scene(app.querySelector('canvas'));bind();}
function bind(){app.querySelector('[data-sound]').onclick=async()=>{if(audio.enabled&&!audio.muted){audio.muted=true;audio.enabled=false;}else{await audio.unlock(true);audio.play('round');}tell('preference',{key:'museum-sound-muted-'+role,value:audio.muted?'1':'0'});refreshSound();};app.querySelector('[data-music]')?.addEventListener('click',async()=>{audio.music=!audio.music;if(audio.music&&!audio.enabled)await audio.unlock();tell('preference',{key:'museum-music-muted-display',value:audio.music?'0':'1'});refreshSound();});
 const ring=app.querySelector('.joystick');if(ring){const move=e=>{e.preventDefault();const value=stickValue(e.clientX,e.clientY,ring.getBoundingClientRect());stick={x:value.x,y:value.y};ring.querySelector('.joystick-knob').style.transform=`translate(calc(-50% + ${value.offsetX}px),calc(-50% + ${value.offsetY}px))`;input();};ring.onpointerdown=e=>{if(!enabled()||pointer!==null)return;e.preventDefault();pointer=e.pointerId;audio.unlock();try{ring.setPointerCapture(pointer);}catch{}move(e);input(true);};ring.onpointermove=e=>{if(e.pointerId===pointer)move(e);};const release=e=>{if(e.pointerId!==pointer)return;pointer=null;stick=null;ring.querySelector('.joystick-knob').style.transform='translate(-50%,-50%)';input(true);};ring.onpointerup=ring.onpointercancel=ring.onlostpointercapture=release;}
 for(const key of ['jump','drop']){const b=app.querySelector('[data-'+key+']');if(!b)continue;let pressed=null;b.onpointerdown=e=>{if(!enabled()||pressed!==null)return;e.preventDefault();pressed=e.pointerId;audio.unlock();if(key==='jump')jumpHeld=true;else dropHeld=true;b.classList.add('held');try{b.setPointerCapture(pressed);}catch{}input(true);};const release=e=>{if(e.pointerId!==pressed)return;pressed=null;if(key==='jump')jumpHeld=false;else dropHeld=false;b.classList.remove('held');input(true);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=release;}
}
function refreshSound(){const b=app.querySelector('[data-sound]');if(b){b.textContent=audio.enabled&&!audio.muted?'♫':'♪';b.setAttribute('aria-label',t(audio.enabled&&!audio.muted?'mute':'sound'));b.classList.toggle('on',audio.enabled&&!audio.muted);}const m=app.querySelector('[data-music]');if(m)m.textContent=t(audio.music?'music':'musicOff')+' '+(audio.music?'♪':'○');}
function update(){const party=state.party,s=party.community,mobile=role==='controller',me=s?.players.find(p=>p.id===party.you),profilesById=profiles();if(layoutKey!==role+lang){layoutKey=role+lang;setup();}audio.role=role;audio.phase=state.phase;document.documentElement.lang=lang;refreshSound();
 let shown=s;if(!s){const roster=party.players.filter(p=>!p.spectator).slice(0,8),key=roster.map(p=>p.id).join(',')+'|'+party.options?.arena;if(key!==selectionKey||!preview){selectionKey=key;preview=new Tag(roster.length?roster:[{id:'preview-a',number:1},{id:'preview-b',number:2}],null,{seed:57,arena:party.options?.arena});preview.advance(.05);}shown=preview.snapshot(party.you);}
 const paused=state.phase==='paused',lobby=state.phase==='ready',finished=state.phase==='ended'||state.phase==='solved'||s?.phase==='finished',intermission=s?.phase==='intermission';
 app.querySelector('.tag-app').classList.toggle('finished',finished);scene.update(shown,profilesById,paused||lobby,inputValue(stick,keys,jumpHeld,dropHeld));
 app.querySelector('.lobby').hidden=!lobby;app.querySelector('.scene').classList.toggle('waiting',lobby);const lineup=app.querySelector('.lineup');if(lobby){const listKey=JSON.stringify(party.players.map(p=>[p.id,p.name,p.connected]));if(lineup.dataset.key!==listKey){lineup.dataset.key=listKey;lineup.innerHTML=party.players.filter(p=>!p.spectator).map((p,i)=>`<span>${avatar(COLORS[i%8],i+1)}<b>${esc(p.name||'#'+(i+1))}</b></span>`).join('');}}
 app.querySelector('.arena-name').textContent=shown.arena.title[lang]||shown.arena.title.en;app.querySelector('.round-number').textContent=lobby?`${party.players.filter(p=>!p.spectator).length} / 8 ${t('players')}`:`${t('round')} ${shown.round} / ${shown.rounds}`;
 const score=app.querySelector('.scoreboard'),scoreKey=JSON.stringify([lobby,shown.players.map(p=>[p.id,p.score]),shown.tagger,party.players.map(p=>[p.name,p.connected]),lang]);if(score.dataset.key!==scoreKey){score.dataset.key=scoreKey;score.innerHTML=shown.players.map(p=>`<div class="score-card ${shown.tagger===p.id&&!lobby?'it':''}" style="--player:${p.color}"><span class="chip">${p.number}</span><span class="score-name">${esc(profilesById[p.id]?.name||'#'+p.number)}</span><strong>${p.score}</strong>${shown.tagger===p.id&&!lobby?`<small>${t('tagger')}</small>`:''}</div>`).join('');}
 const seconds=Math.max(0,Math.ceil(intermission?shown.intermission:shown.left));app.querySelector('.timer b').textContent=finished?'★':seconds;app.querySelector('.timer').classList.toggle('urgent',!intermission&&seconds<=5&&!finished&&!lobby);app.querySelector('.timer').hidden=lobby;
 if(mobile){app.querySelector('.phone-controls').hidden=lobby||finished;const identity=me||shown.players[0],name=profilesById[party.you]?.name||'#'+(identity?.number||''),self=app.querySelector('.portrait'),selfKey=(identity?.color||COLORS[0])+name;if(self.dataset.key!==selfKey){self.dataset.key=selfKey;self.innerHTML=avatar(identity?.color||COLORS[0],identity?.number||1);}app.querySelector('.your-name').textContent=name;app.querySelector('.chase-status').textContent=!me?t('spectator'):paused?t('paused'):intermission?t(shown.lastLoser===me.id?'lost':'survived'):shown.tagger===me.id?t('youIt'):t('run');app.querySelector('.identity').classList.toggle('it',Boolean(me&&shown.tagger===me.id));app.querySelector('.pads').classList.toggle('disabled',!enabled());for(const b of app.querySelectorAll('[data-jump],[data-drop]'))b.disabled=!enabled();app.querySelector('.double').textContent=shown.options.doubleJump?t('double'):'';if(!enabled())stop();}
 const tagged=profilesById[shown.tagger];app.querySelector('.tagger-name').textContent=lobby?t('tagline'):t('tagger')+' · '+(tagged?.name||'');
 const overlay=app.querySelector('.center-overlay'),overlayKey=JSON.stringify([lang,lobby,paused,finished,intermission,state.phase==='intro',shown.round,shown.lastLoser,shown.winners,party.you]);overlay.hidden=!(paused||finished||intermission||state.phase==='intro');if(overlay.dataset.key!==overlayKey){overlay.dataset.key=overlayKey;overlay.innerHTML=paused?`<div><span class="eyebrow">PAUSE</span><h2>${t('paused')}</h2></div>`:state.phase==='intro'?`<div><p class="eyebrow">${t('countdown')}</p><h2>${t('tagline')}</h2></div>`:intermission?`<div><span class="eyebrow">${t('round')} ${shown.round}</span><h2>${esc(profilesById[shown.lastLoser]?.name||'')}<br>${t('lost')}</h2><p>${t('next')}…</p></div>`:finished?`<div><p class="eyebrow">${t(shown.winners?.length>1?'draw':'winner')}</p><h2>${shown.winners?.length?shown.winners.map(id=>esc(profilesById[id]?.name||'#'+shown.players.find(p=>p.id===id)?.number)).join(' · '):t('finished')}</h2><div class="podium">${shown.players.slice().sort((a,b)=>b.score-a.score).map(p=>`<span>${avatar(p.color,p.number)}<b>${esc(profilesById[p.id]?.name||'#'+p.number)}</b><strong>${p.score} ${t('score')}</strong></span>`).join('')}</div>${mobile?`<button class="again" data-again>↻ ${t('again')}</button>`:''}</div>`:'';overlay.querySelector('[data-again]')?.addEventListener('click',()=>send('playAgain').catch(()=>toast(t('error'))));}
 const banner=app.querySelector('.tag-banner');if(s){if(lastRound!==s.round){lastRound=s.round;banner.textContent=t('round')+' '+s.round;banner.classList.add('visible');clearTimeout(update.bannerTimer);update.bannerTimer=setTimeout(()=>banner.classList.remove('visible'),1300);}for(const event of s.events){if(event.id<=lastEvent)continue;if(s.time-event.time<.7){if(event.type==='tag'){banner.textContent=(profilesById[event.player]?.name||'')+' · '+t('tag');banner.classList.add('visible');clearTimeout(update.bannerTimer);update.bannerTimer=setTimeout(()=>banner.classList.remove('visible'),1050);}if(role==='display'||event.player===party.you||['round','roundEnd','win'].includes(event.type))audio.play(event.type);}lastEvent=Math.max(lastEvent,event.id);}if(seconds<=5&&seconds!==lastSecond&&!intermission&&state.phase==='playing'){audio.play('tick');}lastSecond=seconds;}
 if(lastPhase!==state.phase){if(paused)audio.play('pause');else if(lastPhase==='paused')audio.play('round');lastPhase=state.phase;}
}
addEventListener('message',e=>{if(e.source!==parent||e.data?.retroMuseum!==1)return;const m=e.data;if(m.type==='ack'||m.type==='error'){const wait=pending.get(m.id);if(wait){clearTimeout(wait.timer);pending.delete(m.id);m.type==='ack'?wait.resolve():wait.reject(Error(m.code||m.message));}return;}if(m.type==='suspend'){stop();return;}if(m.type!=='state')return;state=m.state;role=m.role;lang=state.language||'en';if(m.preferences?.['museum-sound-muted-'+role]==='1'){audio.muted=true;audio.enabled=false;}if(m.preferences?.['museum-music-muted-display']==='1')audio.music=false;if(match!==state.party.id){stop();match=state.party.id;lastEvent=0;lastRound=0;lastSecond=-1;layoutKey='';selectionKey='';preview=null;}update();if(m.renderId)tell('rendered',{renderId:m.renderId});});
addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});addEventListener('keydown',e=>{if(!enabled()||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','a','d','w','s',' '].includes(e.key))return;e.preventDefault();keys.add(e.key);audio.unlock();input(true);});addEventListener('keyup',e=>{if(keys.delete(e.key)){e.preventDefault();input(true);}});tell('ready',{renderAck:true});
